### ISSUE TITLE
2dsphere index in MongoDB

### ISSUE THREAD

**Issue by fallanic** [jbielick/boundaries.io#1]
Hi,

first thing, I want to say that I'm pretty impressed by boundaries.io, this is super neat, congrats.

I'm currently trying to create a geojson file of the US zip codes using the 2015 census shapefile, and then store it in a Mongo database.

No problem for the GeoJson file creation (QGIS, or mapshaper make it easy enough), or storing the data in Mongo, my problem is when I create the 2dsphere index on the field containing the feature and coordinates, I always get a "can't extract geokeys" error.

It looks like it happens with nested polygons in features

![screen shot 2015-10-02 at 17 24 41](https://cloud.githubusercontent.com/assets/1240520/10259143/a125222e-692a-11e5-810c-5cbe20924d38.png)

Do you have any advice or workaround? How did you proceed on your end?

It would be awesome to provide instructions in the README of this project (I would be very happy to help if needed).

Thanks in advance!

PS : here is the feature from the screenshot

    {
        "type" : "Polygon",
        "coordinates" : [
            [
                [
                    -87.13203999999999,
                    38.00288
                ],
                [
                    -87.13103,
                    38.002900000000004
                ],
                [
                    -87.12747999999999,
                    38.00288
                ],
                [
                    -87.12290999999999,
                    38.00282
                ],
                [
                    -87.12152,
                    38.00285
                ],
                [
                    -87.11852,
                    38.00278
                ],
                [
                    -87.11854,
                    37.999190000000006
                ],
                [
                    -87.11856999999999,
                    37.998020000000004
                ],
                [
                    -87.11854,
                    37.99613000000001
                ],
                [
                    -87.11847999999999,
                    37.99555000000001
                ],
                [
                    -87.1182,
                    37.99461
                ],
                [
                    -87.1182,
                    37.991679999999995
                ],
                [
                    -87.11852999999999,
                    37.989779999999996
                ],
                [
                    -87.11862,
                    37.98852
                ],
                [
                    -87.11825,
                    37.987049999999996
                ],
                [
                    -87.11777,
                    37.98538
                ],
                [
                    -87.11723,
                    37.984069999999996
                ],
                [
                    -87.11622000000001,
                    37.981899999999996
                ],
                [
                    -87.11582999999999,
                    37.981139999999996
                ],
                [
                    -87.11461000000001,
                    37.980079999999994
                ],
                [
                    -87.11296,
                    37.97898
                ],
                [
                    -87.11234999999999,
                    37.978730000000006
                ],
                [
                    -87.11106000000001,
                    37.97845
                ],
                [
                    -87.11064,
                    37.97831000000001
                ],
                [
                    -87.1101,
                    37.97792
                ],
                [
                    -87.10937999999999,
                    37.97703
                ],
                [
                    -87.10929999999999,
                    37.976510000000005
                ],
                [
                    -87.10927,
                    37.9738
                ],
                [
                    -87.1074,
                    37.97379
                ],
                [
                    -87.09908,
                    37.9738
                ],
                [
                    -87.09691000000001,
                    37.97222
                ],
                [
                    -87.09549,
                    37.970859999999995
                ],
                [
                    -87.09394,
                    37.97002
                ],
                [
                    -87.09134,
                    37.96787
                ],
                [
                    -87.0892,
                    37.966590000000004
                ],
                [
                    -87.08792000000001,
                    37.96573000000001
                ],
                [
                    -87.0861,
                    37.96421
                ],
                [
                    -87.08545,
                    37.96347
                ],
                [
                    -87.0851,
                    37.96262
                ],
                [
                    -87.08483,
                    37.962210000000006
                ],
                [
                    -87.08413,
                    37.96154
                ],
                [
                    -87.08282999999999,
                    37.96047
                ],
                [
                    -87.08230999999999,
                    37.95993
                ],
                [
                    -87.08194,
                    37.95934
                ],
                [
                    -87.08587999999999,
                    37.95939
                ],
                [
                    -87.09143,
                    37.959439999999994
                ],
                [
                    -87.09145000000001,
                    37.957899999999995
                ],
                [
                    -87.09315000000001,
                    37.95719999999999
                ],
                [
                    -87.09366000000001,
                    37.956939999999996
                ],
                [
                    -87.09504,
                    37.95672
                ],
                [
                    -87.09568,
                    37.95671
                ],
                [
                    -87.09636,
                    37.95635
                ],
                [
                    -87.09719000000001,
                    37.955999999999996
                ],
                [
                    -87.09758000000001,
                    37.95575
                ],
                [
                    -87.09814,
                    37.955639999999995
                ],
                [
                    -87.09842,
                    37.95517
                ],
                [
                    -87.10032999999999,
                    37.95387999999999
                ],
                [
                    -87.10029,
                    37.95292
                ],
                [
                    -87.10033999999999,
                    37.952279999999995
                ],
                [
                    -87.10025,
                    37.951049999999995
                ],
                [
                    -87.10006999999999,
                    37.946079999999995
                ],
                [
                    -87.10006999999999,
                    37.9449
                ],
                [
                    -87.10552999999999,
                    37.94493
                ],
                [
                    -87.10511,
                    37.947799999999994
                ],
                [
                    -87.10481,
                    37.948550000000004
                ],
                [
                    -87.10533999999998,
                    37.94858
                ],
                [
                    -87.11046,
                    37.94856
                ],
                [
                    -87.11379,
                    37.94846
                ],
                [
                    -87.11382,
                    37.946310000000004
                ],
                [
                    -87.11372,
                    37.94467999999999
                ],
                [
                    -87.11382,
                    37.9397
                ],
                [
                    -87.11388,
                    37.938140000000004
                ],
                [
                    -87.11406000000001,
                    37.93699
                ],
                [
                    -87.11425000000001,
                    37.93681
                ],
                [
                    -87.11507999999999,
                    37.93677
                ],
                [
                    -87.11655,
                    37.93681
                ],
                [
                    -87.1185,
                    37.93677
                ],
                [
                    -87.11849,
                    37.93496
                ],
                [
                    -87.11859,
                    37.93224
                ],
                [
                    -87.11866,
                    37.92893000000001
                ],
                [
                    -87.1374,
                    37.92718
                ],
                [
                    -87.14121000000002,
                    37.9268
                ],
                [
                    -87.14123000000001,
                    37.924730000000004
                ],
                [
                    -87.14121000000002,
                    37.92237000000001
                ],
                [
                    -87.14123000000001,
                    37.9192
                ],
                [
                    -87.1413,
                    37.91621
                ],
                [
                    -87.14412000000002,
                    37.91625
                ],
                [
                    -87.15046999999998,
                    37.916399999999996
                ],
                [
                    -87.15056999999999,
                    37.91257
                ],
                [
                    -87.15055,
                    37.91175
                ],
                [
                    -87.15062999999999,
                    37.90848
                ],
                [
                    -87.15069,
                    37.903659999999995
                ],
                [
                    -87.15072999999998,
                    37.89546
                ],
                [
                    -87.15075999999999,
                    37.89287
                ],
                [
                    -87.15079999999999,
                    37.88761999999999
                ],
                [
                    -87.16716000000001,
                    37.887609999999995
                ],
                [
                    -87.16944,
                    37.88761999999999
                ],
                [
                    -87.16956,
                    37.88341
                ],
                [
                    -87.16963,
                    37.88207
                ],
                [
                    -87.16966000000001,
                    37.88025999999999
                ],
                [
                    -87.17639999999999,
                    37.8803
                ],
                [
                    -87.17860999999999,
                    37.88035
                ],
                [
                    -87.18328,
                    37.88037
                ],
                [
                    -87.18517999999999,
                    37.88043
                ],
                [
                    -87.18612999999999,
                    37.880359999999996
                ],
                [
                    -87.19239999999999,
                    37.88041
                ],
                [
                    -87.19709,
                    37.880419999999994
                ],
                [
                    -87.19698,
                    37.88351
                ],
                [
                    -87.19692,
                    37.88767999999999
                ],
                [
                    -87.20076999999999,
                    37.88614
                ],
                [
                    -87.20365000000001,
                    37.884949999999996
                ],
                [
                    -87.20509,
                    37.884589999999996
                ],
                [
                    -87.20661000000001,
                    37.88443999999999
                ],
                [
                    -87.20717,
                    37.884269999999994
                ],
                [
                    -87.20829,
                    37.884069999999994
                ],
                [
                    -87.20944,
                    37.88411
                ],
                [
                    -87.21079,
                    37.88439999999999
                ],
                [
                    -87.21142000000002,
                    37.884429999999995
                ],
                [
                    -87.21214,
                    37.88423999999999
                ],
                [
                    -87.21434,
                    37.88316
                ],
                [
                    -87.21720000000002,
                    37.882
                ],
                [
                    -87.2203,
                    37.88053
                ],
                [
                    -87.2249,
                    37.880539999999996
                ],
                [
                    -87.22957,
                    37.880649999999996
                ],
                [
                    -87.2299,
                    37.88146999999999
                ],
                [
                    -87.22982999999999,
                    37.88185999999999
                ],
                [
                    -87.22999,
                    37.88345999999999
                ],
                [
                    -87.23003,
                    37.88457999999999
                ],
                [
                    -87.23058,
                    37.885679999999994
                ],
                [
                    -87.23073,
                    37.886269999999996
                ],
                [
                    -87.2307,
                    37.88701
                ],
                [
                    -87.23082000000001,
                    37.88791
                ],
                [
                    -87.23107,
                    37.88858
                ],
                [
                    -87.23155000000001,
                    37.889359999999996
                ],
                [
                    -87.23258,
                    37.89059
                ],
                [
                    -87.23302000000001,
                    37.89133
                ],
                [
                    -87.23312000000001,
                    37.89172
                ],
                [
                    -87.23375,
                    37.892210000000006
                ],
                [
                    -87.23379,
                    37.892570000000006
                ],
                [
                    -87.23462000000002,
                    37.89314
                ],
                [
                    -87.23466000000002,
                    37.89377
                ],
                [
                    -87.23443,
                    37.89399
                ],
                [
                    -87.23490000000001,
                    37.89423
                ],
                [
                    -87.23504,
                    37.89477
                ],
                [
                    -87.23498000000001,
                    37.895250000000004
                ],
                [
                    -87.2359,
                    37.89573000000001
                ],
                [
                    -87.23622000000002,
                    37.89644
                ],
                [
                    -87.23740000000001,
                    37.897059999999996
                ],
                [
                    -87.2381,
                    37.8978
                ],
                [
                    -87.23856,
                    37.89798
                ],
                [
                    -87.23916000000001,
                    37.89857000000001
                ],
                [
                    -87.24068000000001,
                    37.89918
                ],
                [
                    -87.24087,
                    37.89938
                ],
                [
                    -87.24083,
                    37.9
                ],
                [
                    -87.24164000000002,
                    37.900310000000005
                ],
                [
                    -87.24190000000002,
                    37.90089
                ],
                [
                    -87.24257,
                    37.90079
                ],
                [
                    -87.24314000000001,
                    37.901019999999995
                ],
                [
                    -87.24379,
                    37.90147999999999
                ],
                [
                    -87.24422000000003,
                    37.90165
                ],
                [
                    -87.24431000000001,
                    37.901959999999995
                ],
                [
                    -87.24489000000001,
                    37.901849999999996
                ],
                [
                    -87.2459,
                    37.90207
                ],
                [
                    -87.24609000000001,
                    37.90248
                ],
                [
                    -87.24769000000002,
                    37.902530000000006
                ],
                [
                    -87.24782000000002,
                    37.90279
                ],
                [
                    -87.24925000000002,
                    37.90281
                ],
                [
                    -87.25014,
                    37.902710000000006
                ],
                [
                    -87.25016000000001,
                    37.9017
                ],
                [
                    -87.25036,
                    37.901489999999995
                ],
                [
                    -87.25015,
                    37.90115
                ],
                [
                    -87.25027,
                    37.89715
                ],
                [
                    -87.24922000000002,
                    37.89663
                ],
                [
                    -87.24847,
                    37.89608
                ],
                [
                    -87.24732000000002,
                    37.895520000000005
                ],
                [
                    -87.24681000000001,
                    37.89517000000001
                ],
                [
                    -87.24605000000001,
                    37.894439999999996
                ],
                [
                    -87.24560000000001,
                    37.89363
                ],
                [
                    -87.24526000000002,
                    37.89255000000001
                ],
                [
                    -87.24497000000001,
                    37.89129
                ],
                [
                    -87.24473,
                    37.890679999999996
                ],
                [
                    -87.24425000000002,
                    37.889849999999996
                ],
                [
                    -87.24372000000001,
                    37.8891
                ],
                [
                    -87.24277,
                    37.887319999999995
                ],
                [
                    -87.24190000000002,
                    37.88601
                ],
                [
                    -87.24168000000002,
                    37.88552
                ],
                [
                    -87.24087,
                    37.884499999999996
                ],
                [
                    -87.23843,
                    37.88235
                ],
                [
                    -87.23713000000001,
                    37.88099999999999
                ],
                [
                    -87.23653,
                    37.880289999999995
                ],
                [
                    -87.23591,
                    37.87915
                ],
                [
                    -87.23514,
                    37.877089999999995
                ],
                [
                    -87.23790000000001,
                    37.87711
                ],
                [
                    -87.23873999999999,
                    37.87705999999999
                ],
                [
                    -87.23931,
                    37.87683
                ],
                [
                    -87.24021000000002,
                    37.87625
                ],
                [
                    -87.24124000000002,
                    37.87637
                ],
                [
                    -87.24217,
                    37.876999999999995
                ],
                [
                    -87.24276,
                    37.877179999999996
                ],
                [
                    -87.24513,
                    37.877269999999996
                ],
                [
                    -87.24732000000002,
                    37.8773
                ],
                [
                    -87.24932000000001,
                    37.877359999999996
                ],
                [
                    -87.25,
                    37.87734
                ],
                [
                    -87.25071,
                    37.877179999999996
                ],
                [
                    -87.25110000000001,
                    37.87685
                ],
                [
                    -87.25372999999999,
                    37.87501
                ],
                [
                    -87.25502,
                    37.8743
                ],
                [
                    -87.25605,
                    37.873819999999995
                ],
                [
                    -87.25656000000001,
                    37.873479999999994
                ],
                [
                    -87.25907,
                    37.87147999999999
                ],
                [
                    -87.25992000000001,
                    37.87197999999999
                ],
                [
                    -87.26113000000001,
                    37.87292
                ],
                [
                    -87.26159000000001,
                    37.8732
                ],
                [
                    -87.26257,
                    37.874019999999994
                ],
                [
                    -87.26634,
                    37.877269999999996
                ],
                [
                    -87.2681,
                    37.87881
                ],
                [
                    -87.26844,
                    37.87916
                ],
                [
                    -87.26842,
                    37.89158
                ],
                [
                    -87.26842,
                    37.90241
                ],
                [
                    -87.26823,
                    37.90979
                ],
                [
                    -87.26818,
                    37.91495
                ],
                [
                    -87.2681,
                    37.918839999999996
                ],
                [
                    -87.268,
                    37.92477
                ],
                [
                    -87.26795000000001,
                    37.92517000000001
                ],
                [
                    -87.26706000000001,
                    37.92608
                ],
                [
                    -87.26664000000001,
                    37.92633000000001
                ],
                [
                    -87.26631,
                    37.92685
                ],
                [
                    -87.26602000000001,
                    37.9278
                ],
                [
                    -87.26577999999999,
                    37.928180000000005
                ],
                [
                    -87.26476000000001,
                    37.929190000000006
                ],
                [
                    -87.26422000000002,
                    37.92974
                ],
                [
                    -87.26333,
                    37.93041
                ],
                [
                    -87.26208,
                    37.931439999999995
                ],
                [
                    -87.26143,
                    37.93187999999999
                ],
                [
                    -87.25979,
                    37.93325
                ],
                [
                    -87.25895,
                    37.93421
                ],
                [
                    -87.25832999999999,
                    37.93542
                ],
                [
                    -87.25725000000001,
                    37.93642
                ],
                [
                    -87.25617,
                    37.937819999999995
                ],
                [
                    -87.25522000000001,
                    37.93883
                ],
                [
                    -87.25474,
                    37.93943
                ],
                [
                    -87.25331,
                    37.940819999999995
                ],
                [
                    -87.25246,
                    37.941779999999994
                ],
                [
                    -87.25163,
                    37.94254
                ],
                [
                    -87.25064,
                    37.94327
                ],
                [
                    -87.25011,
                    37.94354
                ],
                [
                    -87.24824000000001,
                    37.943979999999996
                ],
                [
                    -87.24649000000001,
                    37.94547
                ],
                [
                    -87.24563,
                    37.946419999999996
                ],
                [
                    -87.24512000000001,
                    37.94713
                ],
                [
                    -87.24426000000003,
                    37.94866
                ],
                [
                    -87.24274,
                    37.95007999999999
                ],
                [
                    -87.24205,
                    37.950829999999996
                ],
                [
                    -87.24130000000001,
                    37.95187999999999
                ],
                [
                    -87.24092000000002,
                    37.95227
                ],
                [
                    -87.24021000000002,
                    37.95249
                ],
                [
                    -87.23906000000001,
                    37.9523
                ],
                [
                    -87.2385,
                    37.951719999999995
                ],
                [
                    -87.23831,
                    37.9509
                ],
                [
                    -87.23804,
                    37.9503
                ],
                [
                    -87.23731000000001,
                    37.94998
                ],
                [
                    -87.23553,
                    37.94993
                ],
                [
                    -87.23483,
                    37.94981
                ],
                [
                    -87.2338,
                    37.9493
                ],
                [
                    -87.23248,
                    37.94818
                ],
                [
                    -87.23190000000001,
                    37.94812
                ],
                [
                    -87.23154000000001,
                    37.9484
                ],
                [
                    -87.23147,
                    37.948750000000004
                ],
                [
                    -87.23166000000002,
                    37.949079999999995
                ],
                [
                    -87.23246,
                    37.949679999999994
                ],
                [
                    -87.23289,
                    37.95014
                ],
                [
                    -87.23305,
                    37.95072
                ],
                [
                    -87.23297,
                    37.95105999999999
                ],
                [
                    -87.23268,
                    37.951319999999996
                ],
                [
                    -87.23118000000001,
                    37.95159999999999
                ],
                [
                    -87.23086,
                    37.95197999999999
                ],
                [
                    -87.23123000000001,
                    37.95307
                ],
                [
                    -87.23117,
                    37.95405999999999
                ],
                [
                    -87.23143,
                    37.95503
                ],
                [
                    -87.23147,
                    37.95577
                ],
                [
                    -87.23110000000001,
                    37.95616
                ],
                [
                    -87.23081,
                    37.95625999999999
                ],
                [
                    -87.23005,
                    37.956199999999995
                ],
                [
                    -87.22919,
                    37.95563
                ],
                [
                    -87.22826,
                    37.955639999999995
                ],
                [
                    -87.22788,
                    37.955999999999996
                ],
                [
                    -87.228,
                    37.95623
                ],
                [
                    -87.2291,
                    37.956579999999995
                ],
                [
                    -87.22932999999999,
                    37.95679
                ],
                [
                    -87.22957,
                    37.95743999999999
                ],
                [
                    -87.22963,
                    37.95843
                ],
                [
                    -87.22982999999999,
                    37.959289999999996
                ],
                [
                    -87.22956,
                    37.95987999999999
                ],
                [
                    -87.22877999999999,
                    37.96047
                ],
                [
                    -87.22826,
                    37.960950000000004
                ],
                [
                    -87.22806999999999,
                    37.9615
                ],
                [
                    -87.22811,
                    37.96189
                ],
                [
                    -87.22834999999999,
                    37.962230000000005
                ],
                [
                    -87.22908,
                    37.96286
                ],
                [
                    -87.22949,
                    37.96368
                ],
                [
                    -87.23010000000001,
                    37.96454
                ],
                [
                    -87.23018,
                    37.96546
                ],
                [
                    -87.22981,
                    37.966590000000004
                ],
                [
                    -87.22925000000001,
                    37.96737
                ],
                [
                    -87.22852999999999,
                    37.968090000000004
                ],
                [
                    -87.22814,
                    37.968610000000005
                ],
                [
                    -87.22788,
                    37.96944
                ],
                [
                    -87.22766000000001,
                    37.969750000000005
                ],
                [
                    -87.22626000000001,
                    37.97121
                ],
                [
                    -87.22569999999999,
                    37.971669999999996
                ],
                [
                    -87.22485,
                    37.97199
                ],
                [
                    -87.22202,
                    37.972100000000005
                ],
                [
                    -87.22032999999999,
                    37.9727
                ],
                [
                    -87.21959000000001,
                    37.97312
                ],
                [
                    -87.21859,
                    37.97396
                ],
                [
                    -87.21719000000002,
                    37.974759999999996
                ],
                [
                    -87.21549,
                    37.97542
                ],
                [
                    -87.21411000000002,
                    37.9759
                ],
                [
                    -87.21347,
                    37.97622
                ],
                [
                    -87.21305000000001,
                    37.97659
                ],
                [
                    -87.21222000000002,
                    37.97773
                ],
                [
                    -87.21123000000001,
                    37.97861
                ],
                [
                    -87.21010000000001,
                    37.97926
                ],
                [
                    -87.20896,
                    37.980219999999996
                ],
                [
                    -87.20727000000001,
                    37.98147999999999
                ],
                [
                    -87.20619,
                    37.98212
                ],
                [
                    -87.20504,
                    37.98269
                ],
                [
                    -87.20338,
                    37.98363
                ],
                [
                    -87.20292,
                    37.98397
                ],
                [
                    -87.20198,
                    37.98485999999999
                ],
                [
                    -87.20148,
                    37.98525
                ],
                [
                    -87.20065000000001,
                    37.98562
                ],
                [
                    -87.1994,
                    37.986019999999996
                ],
                [
                    -87.19812,
                    37.98653
                ],
                [
                    -87.19622000000001,
                    37.987449999999995
                ],
                [
                    -87.19555,
                    37.98808
                ],
                [
                    -87.19497,
                    37.98918
                ],
                [
                    -87.19462000000001,
                    37.98963
                ],
                [
                    -87.1936,
                    37.99063
                ],
                [
                    -87.19266,
                    37.991350000000004
                ],
                [
                    -87.19178,
                    37.9919
                ],
                [
                    -87.19053,
                    37.992490000000004
                ],
                [
                    -87.1895,
                    37.99307
                ],
                [
                    -87.18886999999998,
                    37.99362
                ],
                [
                    -87.18816,
                    37.99441
                ],
                [
                    -87.1872,
                    37.99535000000001
                ],
                [
                    -87.18624,
                    37.996100000000006
                ],
                [
                    -87.18579999999999,
                    37.99602
                ],
                [
                    -87.18321,
                    37.9966
                ],
                [
                    -87.18242999999998,
                    37.996700000000004
                ],
                [
                    -87.18198,
                    37.996500000000005
                ],
                [
                    -87.1816,
                    37.995650000000005
                ],
                [
                    -87.18156,
                    37.99524
                ],
                [
                    -87.18169,
                    37.99477
                ],
                [
                    -87.18226,
                    37.99387
                ],
                [
                    -87.18229,
                    37.99338
                ],
                [
                    -87.18202,
                    37.9928
                ],
                [
                    -87.18078999999999,
                    37.99167
                ],
                [
                    -87.18029999999999,
                    37.991310000000006
                ],
                [
                    -87.17976999999998,
                    37.99116
                ],
                [
                    -87.17850999999999,
                    37.99162
                ],
                [
                    -87.17738999999999,
                    37.99177
                ],
                [
                    -87.17687999999998,
                    37.991730000000004
                ],
                [
                    -87.17412,
                    37.9909
                ],
                [
                    -87.17285999999999,
                    37.990550000000006
                ],
                [
                    -87.17187999999999,
                    37.99036
                ],
                [
                    -87.17098999999999,
                    37.99058
                ],
                [
                    -87.17030999999999,
                    37.99098
                ],
                [
                    -87.16946,
                    37.991730000000004
                ],
                [
                    -87.16806,
                    37.992470000000004
                ],
                [
                    -87.16716000000001,
                    37.99259000000001
                ],
                [
                    -87.16638999999999,
                    37.99286
                ],
                [
                    -87.16499999999999,
                    37.993900000000004
                ],
                [
                    -87.16418,
                    37.99429
                ],
                [
                    -87.16251,
                    37.99465
                ],
                [
                    -87.16101,
                    37.99482
                ],
                [
                    -87.16061,
                    37.994930000000004
                ],
                [
                    -87.15868999999999,
                    37.9958
                ],
                [
                    -87.15813999999999,
                    37.99589
                ],
                [
                    -87.15646,
                    37.99577000000001
                ],
                [
                    -87.15576999999998,
                    37.99544
                ],
                [
                    -87.15509999999999,
                    37.994730000000004
                ],
                [
                    -87.15451,
                    37.99364
                ],
                [
                    -87.15402999999999,
                    37.99315000000001
                ],
                [
                    -87.15356,
                    37.99308
                ],
                [
                    -87.15294999999999,
                    37.99342
                ],
                [
                    -87.15225,
                    37.99436
                ],
                [
                    -87.15121,
                    37.99526
                ],
                [
                    -87.15044999999999,
                    37.996370000000006
                ],
                [
                    -87.14941,
                    37.997530000000005
                ],
                [
                    -87.14872,
                    37.998070000000006
                ],
                [
                    -87.14821,
                    37.99830000000001
                ],
                [
                    -87.14675,
                    37.99853000000001
                ],
                [
                    -87.1461,
                    37.998560000000005
                ],
                [
                    -87.14445,
                    37.99848
                ],
                [
                    -87.14287999999999,
                    37.99848
                ],
                [
                    -87.14214,
                    37.99837000000001
                ],
                [
                    -87.14092000000001,
                    37.998020000000004
                ],
                [
                    -87.14094,
                    37.99942
                ],
                [
                    -87.14153,
                    37.999370000000006
                ],
                [
                    -87.14168000000001,
                    37.999140000000004
                ],
                [
                    -87.14347,
                    37.99954
                ],
                [
                    -87.14095,
                    38.00007
                ],
                [
                    -87.13914,
                    38.00005
                ],
                [
                    -87.13914,
                    38.000679999999996
                ],
                [
                    -87.13646,
                    38.000659999999996
                ],
                [
                    -87.13652,
                    38.00256
                ],
                [
                    -87.13605,
                    38.00292
                ],
                [
                    -87.13203999999999,
                    38.00288
                ]
            ],
            [
                [
                    -87.25231,
                    37.94092
                ],
                [
                    -87.25246999999999,
                    37.940459999999995
                ],
                [
                    -87.25182000000001,
                    37.93997
                ],
                [
                    -87.24958000000001,
                    37.9384
                ],
                [
                    -87.24933,
                    37.93811000000001
                ],
                [
                    -87.24945000000001,
                    37.93548
                ],
                [
                    -87.24946000000001,
                    37.93097
                ],
                [
                    -87.24954000000001,
                    37.928650000000005
                ],
                [
                    -87.24961000000002,
                    37.925450000000005
                ],
                [
                    -87.24947,
                    37.925360000000005
                ],
                [
                    -87.24368000000001,
                    37.92533000000001
                ],
                [
                    -87.24158000000001,
                    37.92535000000001
                ],
                [
                    -87.24147,
                    37.92981
                ],
                [
                    -87.24144000000001,
                    37.93274
                ],
                [
                    -87.24138,
                    37.93445
                ],
                [
                    -87.24135000000001,
                    37.93656
                ],
                [
                    -87.24146000000002,
                    37.94284
                ],
                [
                    -87.23962000000002,
                    37.94287
                ],
                [
                    -87.23559,
                    37.942879999999995
                ],
                [
                    -87.22789,
                    37.94297
                ],
                [
                    -87.22737,
                    37.94359
                ],
                [
                    -87.22628,
                    37.94463
                ],
                [
                    -87.22546,
                    37.94506
                ],
                [
                    -87.22481,
                    37.94506
                ],
                [
                    -87.22404,
                    37.944829999999996
                ],
                [
                    -87.22402000000001,
                    37.94757
                ],
                [
                    -87.22484,
                    37.94755
                ],
                [
                    -87.22586999999999,
                    37.947019999999995
                ],
                [
                    -87.22618,
                    37.946279999999994
                ],
                [
                    -87.22664,
                    37.94583
                ],
                [
                    -87.22710000000001,
                    37.94576
                ],
                [
                    -87.22758,
                    37.945859999999996
                ],
                [
                    -87.22924,
                    37.94581
                ],
                [
                    -87.22999,
                    37.94609
                ],
                [
                    -87.23036,
                    37.94656
                ],
                [
                    -87.23157,
                    37.947579999999995
                ],
                [
                    -87.23188,
                    37.94803
                ],
                [
                    -87.23249,
                    37.94807
                ],
                [
                    -87.23276999999999,
                    37.94825
                ],
                [
                    -87.23383,
                    37.949259999999995
                ],
                [
                    -87.23498000000001,
                    37.94978
                ],
                [
                    -87.23633,
                    37.9499
                ],
                [
                    -87.23745000000001,
                    37.9499
                ],
                [
                    -87.23814,
                    37.95025
                ],
                [
                    -87.23837999999999,
                    37.95071
                ],
                [
                    -87.23872,
                    37.95195
                ],
                [
                    -87.23909,
                    37.952239999999996
                ],
                [
                    -87.24023000000001,
                    37.95242
                ],
                [
                    -87.24068000000001,
                    37.95232
                ],
                [
                    -87.24144000000001,
                    37.95159999999999
                ],
                [
                    -87.24201000000001,
                    37.950739999999996
                ],
                [
                    -87.24326000000002,
                    37.949459999999995
                ],
                [
                    -87.24414000000002,
                    37.94864
                ],
                [
                    -87.24498000000001,
                    37.94713
                ],
                [
                    -87.24553,
                    37.94641
                ],
                [
                    -87.24654000000001,
                    37.94528
                ],
                [
                    -87.24824000000001,
                    37.943859999999994
                ],
                [
                    -87.24944,
                    37.943639999999995
                ],
                [
                    -87.25086,
                    37.94297
                ],
                [
                    -87.25175,
                    37.94223
                ],
                [
                    -87.25133,
                    37.94187999999999
                ],
                [
                    -87.25231,
                    37.94092
                ]
            ]
        ]
    }

**Comment by jbielick** [comment]
@fallanic Thank you!

It's a lot of fun to play with this stuff, isn't it?

A README would be great -- I will see what I can do there.

A couple of questions about your issue:

  1. What version of mongo are you using?
  2. The coordinates for this geo look like a MultiPolygon (self-intersecting?), but the `type` says `Polygon`. Is it possible it should be `MultiPolygon`?
  3. It would also help if you included the command you used to create the index `ensureIndex`. 
  4. Does your document look something like this?

```
    {
        "_id": "55b3c7066404f4b780a363da",
        "type": "Feature",
        "properties": {
            "INTPTLON10": "-079.6354182",
            "CLASSFP10": "B5",
            "FUNCSTAT10": "S",
            "INTPTLAT10": "+35.9514740",
            "ZCTA5CE10": "27283",
            "ALAND10": 68212428,
            "GEOID10": "27283",
            "MTFCC10": "G6350",
            "AWATER10": 586433
        },
        "geometry": {
            "type": "Polygon",
            "coordinates": [
                [
                    [
                        -79.677944,
                        35.942416
                    ],
                    [
                        -79.67742999999999,
                        35.942922
                    ],
```

I think there may need to be a key such as `geometry` for you to index on. Technically, that is the total geojson feature according to the geojson spec.

I'd also recommend using Mongo version >=3.0
I had a number of issues creating the `2dsphere` index in Mongo < 3.0 -- mostly errors like [this](http://stackoverflow.com/questions/23923909/mongodb-2dsphere-index-fails-malformed-geometry). There were a couple bug reports for the 2dsphere extension in mongo as it did not exactly conform to standard and it's been resolved in mongo.

I'd also recommend creating the index ahead of time and then importing your documents. This also resolved some intermittent errors for me.

**Comment by fallanic** [comment]
Thanks for taking the time to help, much appreciated!

1. The newest one, 3.0.6

2. Good point, this one was generated with QGIS. 
My previous tests was with a GeoJson generated by Mapshaper, same kind of issue
    [MongoError: Can't extract geo keys: { _id: ObjectId('56104f08aec8f67aa56df481'), country: "USA", zip: "72002", Location: { type: "MultiPolygon", coordinates: [ [ [ [ -92.67187999999999, 34.73590000000001 ], [ -92.67158999999999, 34.7364 ], [ -92.67106999999999, 34.73648 ], [ -92.67068999999999, 34.73669 ], [ -92.67056999999998, 34.73698 ], [ -92.67058999999999, 34.73794 ], [ -92.67017999999999, 34.73839000000001 ], [ -92.66892, 34.73864 ], [ -92.66842, 34.73886 ], [ -92.66761000000001, 34.73883000000001 ], [ -92.66695, 34.73893000000001 ], [ -92.66496000000001, 34.73876000000001 ], 

3. From a mongo shell
    db.zip_codes.createIndex( { "Location": "2dsphere" } )

4. Yes, except I store the feature in a "Location" attribute, here is another random example :
    { 
    "_id" : ObjectId("560e9b953d7aff8ae84a67f5"), 
    "country" : "USA", 
    "zip" : "43468", 
    "Location" : {
        "type" : "MultiPolygon", 
        "coordinates" : [
            [
                [
                    [
                        -83.34109000000001, 
                        41.602360000000004
                    ], 
                    [
                        -83.34109000000001, 
                        41.60344
                    ], 

Creating the index ahead of time is a good idea, but it fails inserting all "problematic" records (the GeoJson is actually valid but mongo can't index it, so the object is not saved).
I'm currently running an import job with the index created ahead of time, and it looks like dozens are being rejected.

I have a few questions too :

A) what is your preferred tool to convert shapefiles to GeoJson?
B) what version of mongo are you using?
C) did you have to manually tweak some GeoJson values on your end because Mongo couldn't index them? 

Thanks again for helping me through this process!

**Comment by jbielick** [comment]
1. Awesome
2. (see below)
3. Gotcha -- `Location` property makes sense. Looks fine to me.
4. Thanks for outer document context -- looks good

> the GeoJson is actually valid but mongo can't index it, so the object is not saved

This is precisely an issue I was having for quite a while in mongo `< 3.0.0`. Since you're on the newest version, it makes me think mongo might not be the root issue (I'm on `mongod --verison # => db version v3.0.4`)

Take a look at [this example bash script](https://github.com/jbielick/node-streams-workshop/blob/master/mongo-batch-import.sh). That repo is a collection of files I used to pipeline the `zip` files straight from the census bureau website into a new (empty) database / collection in mongo (there's a rethinkdb example, too, but I don't recommend using rethinkdb). You can kick off that script using `make zcta5` or any other geo feature listed in the makefile at the top. 

I never edited any geo documents by hand because it seemed like the fault was somewhere in the conversion from `SHP` to `GeoJSON`. In that bash example you'll see usage of `ogr2ogr`. I highly recommend it for processing / converting the SHP files (it even accepts zip files so you can pipe in and out of a shell). [This line](https://github.com/jbielick/node-streams-workshop/blob/master/mongo-batch-import.sh#L6) seemed to be particularly important in my case, as I think it resolved some slight differences in SHP conversion to geojson. The geojson spec defaults to WGS84 datum and this cli option indicates that should be the output. You can get `ogr2ogr` through a package called `gdal` (`brew install gdal`). Try using `ogr2ogr` for the conversion like in that bash example and let me know if that helps!

**Comment by fallanic** [comment]
You're the man, thank you so much!
