### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by sstalder** [jbielick/boundaries.io#10]
Been seeing this for at least 2 weeks. Can you please review?

**Comment by jbielick** [comment]
The lambda and database were turned off. I'm no longer able to incur the monthly hosting costs.

**Comment by jbielick** [comment]
If you or anyone else are interested in sponsoring the project you can reach me at jbielick@gmail.com. Additionally, the service (source code in this repo and database backup on S3) can be setup by you fairly easily.

**Comment by jbielick** [comment]
API is back up (and free for now). I'll be moving to a paid model with generous request quotas in the near future. Let me know if you're interested in subscribing.
