### ISSUE TITLE
Consider setting up CORS for API

### ISSUE THREAD

**Issue by brambow** [jbielick/boundaries.io#5]
Would be nice to be able to access this with ajax calls in addition to curl.

**Comment by jbielick** [comment]
What origin might you be accessing from? I'm not sure I want to allow all origins at this time, but I could whitelist yours. Additionally, you could run a proxy server in between boundaries.io.

**Comment by brambow** [comment]
Don't worry about it, the proxy is a good idea.  I don't have a specific domain - was working on something for a client but found out that US census has a REST server that pretty much does what I needed.  Will still keep up with this project though!
